.eslintignoreversion: '3.8'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.1
    command: ['start-dev']
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
    ports:
      - "9080:9080"
